# Generated by Django 3.1.1 on 2020-09-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20200930_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='pincode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
